//apply plugin: 'com.android.library'
//android {
//    compileSdkVersion 18
//    //buildToolsVersion "20.0.0"
//
//}

apply plugin: 'java-library'


compileJava{
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
}


buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-gradle-plugin
        //classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.3'
    }
}



//apply plugin: 'com.google.protobuf'


dependencies {
    //compile fileTree(include: ['*.jar'], dir: 'libs')

    //并不传递依赖关系类似idea的provided
    compileOnly files('libs/android.jar')
    compileOnly files('libs/uiautomator.jar')
    //传递依赖关系，且在运行时使用
    compile files('libs/netty-all-4.1.17.Final.jar')
    //compile files('libs/gson-2.8.5.jar')
    compile project(':common_java')

    // https://mvnrepository.com/artifact/com.google.guava/guava
    //compile group: 'com.google.guava', name: 'guava', version: '26.0-android'
    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
    //compile group: 'com.google.protobuf', name: 'protobuf-java', version: '3.5.1'
    //compile group: 'com.google.protobuf', name: 'protobuf-lite', version: '3.0.1'
    //compile 'com.google.protobuf:protoc:3.5.1'
    // https://mvnrepository.com/artifact/io.netty/netty-all
    //compile group: 'io.netty', name: 'netty-all', version: '4.1.17.Final'
    // https://mvnrepository.com/artifact/com.alibaba/fastjson
    //compile group: 'com.alibaba', name: 'fastjson', version: '1.1.70.android'
}


//sourceSets {
//    main {
//        proto {
//            srcDir 'src/main/java/com/testerkit/proto'
//            include '**/*.proto'
//        }
//        java {
//            srcDir 'src/main/java'
//        }
//    }
//}
//protobuf {
//    //这里配置protoc编译器
//    protoc {
//        // https://mvnrepository.com/artifact/com.google.protobuf/protoc
//        artifact = 'com.google.protobuf:protoc:3.5.1'
//    }
//    generateProtoTasks {
//        all().each { task ->
//            task.builtins {
//                remove java
//            }
//            task.builtins {
//                java {}
//                // Add cpp output without any option.
//                // DO NOT omit the braces if you want this builtin to be added.
//                //cpp {}
//            }
//        }
//    }
//    generatedFilesBaseDir = "$projectDir/src"
//}



/**编译目录
//project.ext {
//    dexDir = new File('./build/dex')
//    distDir = new File('./dist')
//}
*/
////jar包发布
//jar {
//    doLast {
//        println 'dex...'
//        tasks.dex.execute()
//    }
//}

/**
 * cmd 命令编译
 "/Users/able/Library/Android/sdk/build-tools/20.0.0/dx" --dex --output=./classes.dex ./bin ./libs/searchstrategy.jar
 "/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/jar" -cvf uitest.jar -C ./ ./classes.dex
 cp ./uitest.jar /Users/able/Desktop/workspace/IdeaProjects/iTestin/tools/
// *
//task dex(dependsOn:jar, type:Exec) {
//    println 'Building dex...'
//    workingDir '.'
//    project.dexDir.mkdirs()
//    println "workingDir:"+workingDir
//    println "buildDir:"+buildDir
//    commandLine androidSdkHome + '/' + androidSdkBuildToolsDir + '/' + 'dx', '--dex', '--no-strict', '--output=' + buildDir +'/dex/' + project.name + '.jar', jar.archivePath
//    doLast {
//        tasks.dist.execute()
//    }
//}
////拷贝最终目录
//task dist(dependsOn:dex, type:Copy) {
//    println 'Copy to dist...'
//    project.distDir.mkdirs()
//    from(project.dexDir)
//    into(project.distDir)
//    include('*.jar')
//}

 **/

//有问题
//task release(type:Exec) {
//    group "test"
//    commandLine './release.sh',dxFile,jarFile,'./libs/netty-all-4.1.17.Final.jar'
//}

//打包jar文件并且带有cmpile的依赖包,依赖jar包的compile依赖jar包也会包含
jar {
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

task release2(dependsOn:build,type:Exec) {
    group "test"
//    File destDir = new File('./dest')
//    destDir.deleteDir()
//    destDir.mkdirs()
    commandLine dxFile, '--dex', '--no-strict', '--output=./dest/' + project.name + '.jar', jar.archivePath //,'./libs/netty-all-4.1.17.Final.jar','./libs/gson-2.8.5.jar'
}

task run(type:Exec) {
    group "test"
    commandLine './run.sh','uiautomator'
}