#androidSdkHome – Point to the root directory of android SDK.
androidSdkHome=/Users/able/Library/Android/sdk
#androidSdkTarget – Is the target, points to a directory inside platforms. uia >= api 16
androidSdkTarget=android-16
#androidSdkBuildToolsDir – Location of dx program.
androidSdkBuildToolsDir=build-tools/20.0.0
#java jdl
jarFile=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/jar
dxFile=/Users/able/Library/Android/sdk/build-tools/20.0.0/dx
