apply plugin: 'com.android.application'

android {


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 28
    //gradle自带编译工具
    //buildToolsVersion '28.0.2'
    defaultConfig {
        applicationId "com.testerkit"
        testApplicationId "com.testerkit.uia2"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode 20200612
        versionName "2020.06.12"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        applicationVariants.all { variant ->
            variant.outputs.all { output ->
                outputFileName = outputFileName.replace('app-debug.apk', "target-v${defaultConfig.versionName}.apk")
            }
        }

        android.testVariants.all { variant ->
            //开始构建当前变体的即时时间
            def time = currentTime()
            variant.outputs.all { output ->
                output.processManifest.doLast {
                    println "**************************************"
                    println "startTime: ${time}"
                    /**
                     * Stores the path to the maifest.
                     * "$manifestOutputDirectory"等价output.processManifest.manifestOutputDirectory
                     * output.processResources.manifestFile 直接输出文件路径
                     */

//                    println "$manifestOutputDirectory"
//                    println output.processManifest.manifestOutputDirectory
//                    println output.processResources.manifestFile
                    String manifestPath = "$manifestOutputDirectory/AndroidManifest.xml"
                    String fileTest = "src/androidTest/AndroidManifest.xml";
                    // Stores the contents of the manifest.
                    def manifestContent = file(fileTest).getText()
                    //println manifestContent
                    // Changes the version code in the stored text.
                    manifestContent = manifestContent.replace('android:versionCode="1"', String.format('android:versionCode="%s"', defaultConfig.versionCode))
                    manifestContent = manifestContent.replace('android:versionName="1"', String.format('android:versionName="%s"', defaultConfig.versionName))
                    // Overwrites the manifest with the new text.
                    file(manifestPath).write(manifestContent)
                    println "endTime:  ${currentTime()}"
                    println "**************************************"
                }
                outputFileName = outputFileName.replace('app-debug-androidTest.apk', "uia2-v${defaultConfig.versionName}.apk")
            }
        }
    }
    //解决编译错误
    lintOptions {
        abortOnError false
    }

    //统一设置了androidTest对应的内容，优先级最高
    sourceSets{
        androidTest{
            //不起作用
            manifest.srcFile 'src/androidTest/AndroidManifest.xml'
            //setRoot 'src/androidTest'
        }
    }

}


dependencies {
    // libs
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //App test for UnitTest
    testImplementation 'junit:junit:4.12'
    testImplementation project(':uia1')


    //region App dependencies

    //App compatibility
    //compile 'com.android.support:appcompat-v7:25.3.1'
    implementation 'com.android.support:support-annotations:25.4.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:28.0.0'
    //endregion


    //region AndroidTest server

    //compile 'com.google.guava:guava:18.0'
    // Testing-only dependencies
    // Force usage of support annotations in the test app, since it is internally used by the runner module.
    androidTestImplementation 'com.android.support:support-annotations:25.4.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.0'
    androidTestImplementation 'com.android.support.test:rules:1.0.0'
    // UiAutomator Testing
    androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
    //androidTestCompile 'com.android.support.test.espresso:espresso-core:' + rootProject.espressoVersion;
    androidTestImplementation project(':uia1')
    //endregion
}

/**
 * 获取当前事件
 * @return
 */
def currentTime() {
    return new Date().format("yyyy.MM.dd_HH.mm.ss", TimeZone.getTimeZone("GMT+8"))
}
def currentDay() {
    return new Date().format("yyyy.MM.dd", TimeZone.getTimeZone("GMT+8"))
}