apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '28.0.2'
    defaultConfig {
        applicationId "com.testerkit"
        minSdkVersion 18
        targetSdkVersion 26
        versionCode 20180622
        versionName "2018.06.22"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
//        applicationVariants.all { variant ->
//            variant.outputs.all {
//                outputFileName = outputFileName.replace('debug.apk', "v${defaultConfig.versionName}.apk")
//            }
//        }
    }
    lintOptions {
        abortOnError false
    }

}
dependencies {
    // 将jar包打在test apk中，否则会无法启动测试
    androidTestImplementation fileTree(include: ['*.jar'], dir: 'libs')
    //App test for UnitTest
    implementation 'junit:junit:4.12'
    //App compatibility
    //compile 'com.android.support:appcompat-v7:25.3.1'
    // App dependencies
    implementation 'com.android.support:support-annotations:25.4.0'
    //compile 'com.google.guava:guava:18.0'
    // Testing-only dependencies
    // Force usage of support annotations in the test app, since it is internally used by the runner module.
    androidTestImplementation 'com.android.support:support-annotations:25.4.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.0'
    androidTestImplementation 'com.android.support.test:rules:1.0.0'
    // UiAutomator Testing
    androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
    //androidTestCompile 'com.android.support.test.espresso:espresso-core:' + rootProject.espressoVersion;
    androidTestImplementation project(':uia1')
}


/**==================注意==============
 * 1、如果重新编译了项目或者clear，需要注释一下代码，编译成功后再恢复代码编译一次即可
 * 忽略AndroidTestManifest的合并
 */
// android.testVariants.all{ variant ->
//     // 开始构建当前变体的即时时间
//     def currentTime = buildTime()
//
//     variant.outputs.each { output ->
//         output.processResources.manifestFile = file('src/androidTest/AndroidManifest.xml')
//         output.processManifest.enabled=false
//         println "[testVariants][in]**************************************"
//         println "currentTime: ${currentTime}"
//         println "variant: ${output.name}"
//         println "buildType: ${variant.buildType.name}"
//         println "flavor: ${variant.flavorName}"
//         println "manifest:  ${output.processResources.manifestFile}"
//         //将生成的apk文件保存至根目录的_apk文件下
//         def outputFile = output.outputFile
//         println "outputFile:  ${outputFile}"
//         println "[testVariants][out]**************************************"
//     }
// }


//https://blog.csdn.net/u013394527/article/details/50977701
//android.applicationVariants.all { variant ->
//    // 开始构建当前变体的即时时间
//    def currentTime = buildTime()
//
//    variant.outputs.each { output ->
//        println "[applicationVariants][in]**************************************"
//        println "currentTime: ${currentTime}"
//        println "variant: ${output.name}"
//        println "buildType: ${variant.buildType.name}"
//        println "flavor: ${variant.flavorName}"
//        println "manifest:  ${output.processResources.manifestFile}"
//        //将生成的apk文件保存至根目录的_apk文件下
//        def outputFile = output.outputFile
//        println "outputFile:  ${outputFile}"
//        println "[applicationVariants][out]**************************************"
//    }
//}
//def buildTime() {
//    return new Date().format("yyyy.MM.dd_HH.mm.ss", TimeZone.getTimeZone("UTC"))
//}

