//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: wire.proto
//
//package com.testerkit.proto;
//
//public final class Wire {
//  private Wire() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  /**
//   * Protobuf enum {@code com.testerkit.ptoto.MessageType}
//   */
//  public enum MessageType
//      implements com.google.protobuf.ProtocolMessageEnum {
//    /**
//     * <code>CAPTURE = 0;</code>
//     */
//    CAPTURE(0),
//    UNRECOGNIZED(-1),
//    ;
//
//    /**
//     * <code>CAPTURE = 0;</code>
//     */
//    public static final int CAPTURE_VALUE = 0;
//
//
//    public final int getNumber() {
//      if (this == UNRECOGNIZED) {
//        throw new java.lang.IllegalArgumentException(
//            "Can't get the number of an unknown enum value.");
//      }
//      return value;
//    }
//
//    /**
//     * @deprecated Use {@link #forNumber(int)} instead.
//     */
//    @java.lang.Deprecated
//    public static MessageType valueOf(int value) {
//      return forNumber(value);
//    }
//
//    public static MessageType forNumber(int value) {
//      switch (value) {
//        case 0: return CAPTURE;
//        default: return null;
//      }
//    }
//
//    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
//        internalGetValueMap() {
//      return internalValueMap;
//    }
//    private static final com.google.protobuf.Internal.EnumLiteMap<
//        MessageType> internalValueMap =
//          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
//            public MessageType findValueByNumber(int number) {
//              return MessageType.forNumber(number);
//            }
//          };
//
//    public final com.google.protobuf.Descriptors.EnumValueDescriptor
//        getValueDescriptor() {
//      return getDescriptor().getValues().get(ordinal());
//    }
//    public final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptorForType() {
//      return getDescriptor();
//    }
//    public static final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptor() {
//      return com.testerkit.proto.Wire.getDescriptor().getEnumTypes().get(0);
//    }
//
//    private static final MessageType[] VALUES = values();
//
//    public static MessageType valueOf(
//        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
//      if (desc.getType() != getDescriptor()) {
//        throw new java.lang.IllegalArgumentException(
//          "EnumValueDescriptor is not for this type.");
//      }
//      if (desc.getIndex() == -1) {
//        return UNRECOGNIZED;
//      }
//      return VALUES[desc.getIndex()];
//    }
//
//    private final int value;
//
//    private MessageType(int value) {
//      this.value = value;
//    }
//
//    // @@protoc_insertion_point(enum_scope:com.testerkit.ptoto.MessageType)
//  }
//
//  public interface EnvelopeOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:com.testerkit.ptoto.Envelope)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>uint32 id = 1;</code>
//     */
//    int getId();
//
//    /**
//     * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//     */
//    int getTypeValue();
//    /**
//     * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//     */
//    com.testerkit.proto.Wire.MessageType getType();
//
//    /**
//     * <code>bytes message = 3;</code>
//     */
//    com.google.protobuf.ByteString getMessage();
//  }
//  /**
//   * Protobuf type {@code com.testerkit.ptoto.Envelope}
//   */
//  public  static final class Envelope extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:com.testerkit.ptoto.Envelope)
//      EnvelopeOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use Envelope.newBuilder() to construct.
//    private Envelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Envelope() {
//      id_ = 0;
//      type_ = 0;
//      message_ = com.google.protobuf.ByteString.EMPTY;
//    }
//
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private Envelope(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new java.lang.NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownFieldProto3(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 8: {
//
//              id_ = input.readUInt32();
//              break;
//            }
//            case 16: {
//              int rawValue = input.readEnum();
//
//              type_ = rawValue;
//              break;
//            }
//            case 26: {
//
//              message_ = input.readBytes();
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.testerkit.proto.Wire.internal_static_com_testerkit_ptoto_Envelope_descriptor;
//    }
//
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.testerkit.proto.Wire.internal_static_com_testerkit_ptoto_Envelope_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.testerkit.proto.Wire.Envelope.class, com.testerkit.proto.Wire.Envelope.Builder.class);
//    }
//
//    public static final int ID_FIELD_NUMBER = 1;
//    private int id_;
//    /**
//     * <code>uint32 id = 1;</code>
//     */
//    public int getId() {
//      return id_;
//    }
//
//    public static final int TYPE_FIELD_NUMBER = 2;
//    private int type_;
//    /**
//     * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//     */
//    public int getTypeValue() {
//      return type_;
//    }
//    /**
//     * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//     */
//    public com.testerkit.proto.Wire.MessageType getType() {
//      com.testerkit.proto.Wire.MessageType result = com.testerkit.proto.Wire.MessageType.valueOf(type_);
//      return result == null ? com.testerkit.proto.Wire.MessageType.UNRECOGNIZED : result;
//    }
//
//    public static final int MESSAGE_FIELD_NUMBER = 3;
//    private com.google.protobuf.ByteString message_;
//    /**
//     * <code>bytes message = 3;</code>
//     */
//    public com.google.protobuf.ByteString getMessage() {
//      return message_;
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (id_ != 0) {
//        output.writeUInt32(1, id_);
//      }
//      if (type_ != com.testerkit.proto.Wire.MessageType.CAPTURE.getNumber()) {
//        output.writeEnum(2, type_);
//      }
//      if (!message_.isEmpty()) {
//        output.writeBytes(3, message_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (id_ != 0) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeUInt32Size(1, id_);
//      }
//      if (type_ != com.testerkit.proto.Wire.MessageType.CAPTURE.getNumber()) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeEnumSize(2, type_);
//      }
//      if (!message_.isEmpty()) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(3, message_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.testerkit.proto.Wire.Envelope)) {
//        return super.equals(obj);
//      }
//      com.testerkit.proto.Wire.Envelope other = (com.testerkit.proto.Wire.Envelope) obj;
//
//      boolean result = true;
//      result = result && (getId()
//          == other.getId());
//      result = result && type_ == other.type_;
//      result = result && getMessage()
//          .equals(other.getMessage());
//      result = result && unknownFields.equals(other.unknownFields);
//      return result;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + ID_FIELD_NUMBER;
//      hash = (53 * hash) + getId();
//      hash = (37 * hash) + TYPE_FIELD_NUMBER;
//      hash = (53 * hash) + type_;
//      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
//      hash = (53 * hash) + getMessage().hashCode();
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.testerkit.proto.Wire.Envelope parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.testerkit.proto.Wire.Envelope prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code com.testerkit.ptoto.Envelope}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:com.testerkit.ptoto.Envelope)
//        com.testerkit.proto.Wire.EnvelopeOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.testerkit.proto.Wire.internal_static_com_testerkit_ptoto_Envelope_descriptor;
//      }
//
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.testerkit.proto.Wire.internal_static_com_testerkit_ptoto_Envelope_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.testerkit.proto.Wire.Envelope.class, com.testerkit.proto.Wire.Envelope.Builder.class);
//      }
//
//      // Construct using com.testerkit.proto.Wire.Envelope.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        id_ = 0;
//
//        type_ = 0;
//
//        message_ = com.google.protobuf.ByteString.EMPTY;
//
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.testerkit.proto.Wire.internal_static_com_testerkit_ptoto_Envelope_descriptor;
//      }
//
//      public com.testerkit.proto.Wire.Envelope getDefaultInstanceForType() {
//        return com.testerkit.proto.Wire.Envelope.getDefaultInstance();
//      }
//
//      public com.testerkit.proto.Wire.Envelope build() {
//        com.testerkit.proto.Wire.Envelope result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public com.testerkit.proto.Wire.Envelope buildPartial() {
//        com.testerkit.proto.Wire.Envelope result = new com.testerkit.proto.Wire.Envelope(this);
//        result.id_ = id_;
//        result.type_ = type_;
//        result.message_ = message_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, java.lang.Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.testerkit.proto.Wire.Envelope) {
//          return mergeFrom((com.testerkit.proto.Wire.Envelope)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.testerkit.proto.Wire.Envelope other) {
//        if (other == com.testerkit.proto.Wire.Envelope.getDefaultInstance()) return this;
//        if (other.getId() != 0) {
//          setId(other.getId());
//        }
//        if (other.type_ != 0) {
//          setTypeValue(other.getTypeValue());
//        }
//        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
//          setMessage(other.getMessage());
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.testerkit.proto.Wire.Envelope parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (com.testerkit.proto.Wire.Envelope) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private int id_ ;
//      /**
//       * <code>uint32 id = 1;</code>
//       */
//      public int getId() {
//        return id_;
//      }
//      /**
//       * <code>uint32 id = 1;</code>
//       */
//      public Builder setId(int value) {
//
//        id_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>uint32 id = 1;</code>
//       */
//      public Builder clearId() {
//
//        id_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private int type_ = 0;
//      /**
//       * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//       */
//      public int getTypeValue() {
//        return type_;
//      }
//      /**
//       * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//       */
//      public Builder setTypeValue(int value) {
//        type_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//       */
//      public com.testerkit.proto.Wire.MessageType getType() {
//        com.testerkit.proto.Wire.MessageType result = com.testerkit.proto.Wire.MessageType.valueOf(type_);
//        return result == null ? com.testerkit.proto.Wire.MessageType.UNRECOGNIZED : result;
//      }
//      /**
//       * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//       */
//      public Builder setType(com.testerkit.proto.Wire.MessageType value) {
//        if (value == null) {
//          throw new NullPointerException();
//        }
//
//        type_ = value.getNumber();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.com.testerkit.ptoto.MessageType type = 2;</code>
//       */
//      public Builder clearType() {
//
//        type_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
//      /**
//       * <code>bytes message = 3;</code>
//       */
//      public com.google.protobuf.ByteString getMessage() {
//        return message_;
//      }
//      /**
//       * <code>bytes message = 3;</code>
//       */
//      public Builder setMessage(com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        message_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>bytes message = 3;</code>
//       */
//      public Builder clearMessage() {
//
//        message_ = getDefaultInstance().getMessage();
//        onChanged();
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFieldsProto3(unknownFields);
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:com.testerkit.ptoto.Envelope)
//    }
//
//    // @@protoc_insertion_point(class_scope:com.testerkit.ptoto.Envelope)
//    private static final com.testerkit.proto.Wire.Envelope DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.testerkit.proto.Wire.Envelope();
//    }
//
//    public static com.testerkit.proto.Wire.Envelope getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Envelope>
//        PARSER = new com.google.protobuf.AbstractParser<Envelope>() {
//      public Envelope parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new Envelope(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Envelope> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<Envelope> getParserForType() {
//      return PARSER;
//    }
//
//    public com.testerkit.proto.Wire.Envelope getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_testerkit_ptoto_Envelope_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_com_testerkit_ptoto_Envelope_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\nwire.proto\022\023com.testerkit.ptoto\"W\n\010Env" +
//      "elope\022\n\n\002id\030\001 \001(\r\022.\n\004type\030\002 \001(\0162 .com.te" +
//      "sterkit.ptoto.MessageType\022\017\n\007message\030\003 \001" +
//      "(\014*\032\n\013MessageType\022\013\n\007CAPTURE\020\000B\033\n\023com.te" +
//      "sterkit.protoB\004Wireb\006proto3"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_com_testerkit_ptoto_Envelope_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_com_testerkit_ptoto_Envelope_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_com_testerkit_ptoto_Envelope_descriptor,
//        new java.lang.String[] { "Id", "Type", "Message", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
